APP_NAME = "tablebuilder"
TABLE_NAME_MAX_LENGTH = 63
TABLE_FIELD_DEFAULT_STRING_LENGTH = 100
TABLE_FIELD_DEFAULT_STRING_TYPE = "char"

CHAR_STRING_TYPE = "char"
TEXT_STRING_TYPE = "text"
ACCEPTABLE_STRING_TYPES = [CHAR_STRING_TYPE, TEXT_STRING_TYPE]


GENERATE_TABLE_EXCEPTION_MESSAGE = "Something went wrong. Deleting table structure from db."
